import jsPDF from 'jspdf';
import { AnalysisResult } from './types';

export function exportReport(result: AnalysisResult): void {
  const doc = new jsPDF();
  const m = result.metadata;
  let y = 20;

  const addLine = (text: string, size = 10, bold = false) => {
    doc.setFontSize(size);
    doc.setFont('helvetica', bold ? 'bold' : 'normal');
    const lines = doc.splitTextToSize(text, 170);
    if (y + lines.length * (size * 0.5) > 280) {
      doc.addPage();
      y = 20;
    }
    doc.text(lines, 20, y);
    y += lines.length * (size * 0.45) + 4;
  };

  const addSection = (title: string) => {
    y += 4;
    addLine(title, 13, true);
    y += 2;
  };

  // Header
  addLine('METADATA FORENSIC SUITE', 18, true);
  addLine('Forensic Analysis Report', 12, false);
  addLine(`Generated: ${new Date().toISOString()}`, 9);
  y += 6;

  // File Details
  addSection('FILE DETAILS');
  addLine(`Filename: ${m.fileName}`);
  addLine(`Type: ${m.fileType} (${m.mimeType})`);
  addLine(`Size: ${(m.fileSize / 1024).toFixed(2)} KB`);
  addLine(`SHA-256: ${m.sha256Hash}`);
  addLine(`Last Modified: ${m.lastModified.toISOString()}`);
  addLine(`Upload Time: ${m.uploadTimestamp.toISOString()}`);

  // Metadata
  addSection('EXTRACTED METADATA');
  if (m.author) addLine(`Author: ${m.author}`);
  if (m.creationDate) addLine(`Creation Date: ${m.creationDate.toISOString()}`);
  if (m.modificationDate) addLine(`Modification Date: ${m.modificationDate.toISOString()}`);
  if (m.software) addLine(`Software: ${m.software}`);
  if (m.device) addLine(`Device: ${m.device}`);
  if (m.gpsLatitude !== undefined) addLine(`GPS: ${m.gpsLatitude}, ${m.gpsLongitude}`);
  if (m.dimensions) addLine(`Dimensions: ${m.dimensions.width} x ${m.dimensions.height}`);

  // Risk Assessment
  addSection('RISK ASSESSMENT');
  addLine(`Risk Score: ${result.riskScore}/100`);
  addLine(`Risk Level: ${result.riskLevel.toUpperCase()}`);
  addLine(`Integrity Status: ${result.integrityStatus.toUpperCase()}`);

  // Anomalies
  if (result.anomalies.length > 0) {
    addSection('DETECTED ANOMALIES');
    result.anomalies.forEach((a, i) => {
      addLine(`${i + 1}. [${a.severity.toUpperCase()}] ${a.title}`);
      addLine(`   ${a.description}`, 9);
    });
  }

  // Explanation
  addSection('ANALYSIS SUMMARY');
  addLine(result.riskExplanation, 10);

  // Footer
  y += 10;
  addLine('--- End of Report ---', 9);
  addLine('This report was generated by Metadata Forensic Suite.', 8);

  doc.save(`forensic-report-${m.fileName.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`);
}
